
package de.cynapsys.homeautomation.webserviceimpl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import de.cynapsys.homeautomation.webservice.Category;
import de.cynapsys.homeautomation.webservice.CategoryArray;
import de.cynapsys.homeautomation.webservice.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CategoryWebService", targetNamespace = "http://webservice.homeautomation.cynapsys.de/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CategoryWebService {


    /**
     * 
     * @param category
     * @return
     *     returns long
     */
    @WebMethod
    @WebResult(partName = "return")
    public long addCategory(
        @WebParam(name = "Category", partName = "Category")
        Category category);

    /**
     * 
     * @param categoryID
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    public boolean deleteCategory(
        @WebParam(name = "CategoryID", partName = "CategoryID")
        long categoryID);

    /**
     * 
     * @param category
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    public boolean updateCategory(
        @WebParam(name = "Category", partName = "Category")
        Category category);

    /**
     * 
     * @return
     *     returns de.cynapsys.homeautomation.webservice.CategoryArray
     */
    @WebMethod
    @WebResult(partName = "return")
    public CategoryArray getAllCategories();

    /**
     * 
     * @param categoryID
     * @return
     *     returns de.cynapsys.homeautomation.webservice.Category
     */
    @WebMethod
    @WebResult(partName = "return")
    public Category getCategoryByID(
        @WebParam(name = "CategoryID", partName = "CategoryID")
        long categoryID);

}
