
package de.cynapsys.homeautomation.webserviceimpl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CategoryWebServiceImplService", targetNamespace = "http://webserviceImpl.homeautomation.cynapsys.de/")
public class CategoryWebServiceImplService
    extends Service
{

    private final static URL CATEGORYWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CATEGORYWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName CATEGORYWEBSERVICEIMPLSERVICE_QNAME = new QName("http://webserviceImpl.homeautomation.cynapsys.de/", "CategoryWebServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://cynapsys.pagekite.me:80/HomeAutomationHibernate/CategoryWebServiceImplService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CATEGORYWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        CATEGORYWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public CategoryWebServiceImplService() {
        super(__getWsdlLocation(), CATEGORYWEBSERVICEIMPLSERVICE_QNAME);
    }

    public CategoryWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns CategoryWebService
     */
    @WebEndpoint(name = "CategoryWebServiceImplPort")
    public CategoryWebService getCategoryWebServiceImplPort() {
        return super.getPort(new QName("http://webserviceImpl.homeautomation.cynapsys.de/", "CategoryWebServiceImplPort"), CategoryWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CategoryWebService
     */
    @WebEndpoint(name = "CategoryWebServiceImplPort")
    public CategoryWebService getCategoryWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webserviceImpl.homeautomation.cynapsys.de/", "CategoryWebServiceImplPort"), CategoryWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CATEGORYWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw CATEGORYWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return CATEGORYWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
