
package de.cynapsys.homeautomation.webserviceimpl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import de.cynapsys.homeautomation.webservice.Device;
import de.cynapsys.homeautomation.webservice.DeviceArray;
import de.cynapsys.homeautomation.webservice.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DeviceWebService", targetNamespace = "http://webservice.homeautomation.cynapsys.de/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DeviceWebService {


    /**
     * 
     * @param device
     * @return
     *     returns long
     */
    @WebMethod
    @WebResult(partName = "return")
    public long addDevice(
        @WebParam(name = "device", partName = "device")
        Device device);

    /**
     * 
     * @param device
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    public boolean updateDevice(
        @WebParam(name = "device", partName = "device")
        Device device);

    /**
     * 
     * @param deviceID
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    public boolean deleteDevice(
        @WebParam(name = "deviceID", partName = "deviceID")
        long deviceID);

    /**
     * 
     * @return
     *     returns de.cynapsys.homeautomation.webservice.DeviceArray
     */
    @WebMethod
    @WebResult(partName = "return")
    public DeviceArray getAllDevices();

    /**
     * 
     * @param deviceID
     * @return
     *     returns de.cynapsys.homeautomation.webservice.Device
     */
    @WebMethod
    @WebResult(partName = "return")
    public Device getDeviceByID(
        @WebParam(name = "deviceID", partName = "deviceID")
        long deviceID);

    /**
     * 
     * @param roomID
     * @return
     *     returns de.cynapsys.homeautomation.webservice.DeviceArray
     */
    @WebMethod
    @WebResult(partName = "return")
    public DeviceArray getDevicesByRoom(
        @WebParam(name = "RoomID", partName = "RoomID")
        long roomID);

    /**
     * 
     * @param categoryID
     * @return
     *     returns de.cynapsys.homeautomation.webservice.DeviceArray
     */
    @WebMethod
    @WebResult(partName = "return")
    public DeviceArray getDevicesByCategory(
        @WebParam(name = "CategoryID", partName = "CategoryID")
        long categoryID);

    /**
     * 
     * @param deviceID
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(partName = "return")
    public int getValue(
        @WebParam(name = "deviceID", partName = "deviceID")
        long deviceID);

    /**
     * 
     * @param deviceID
     * @param value
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    public boolean setValue(
        @WebParam(name = "deviceID", partName = "deviceID")
        long deviceID,
        @WebParam(name = "value", partName = "value")
        int value);

}
