
package de.cynapsys.homeautomation.webserviceimpl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import de.cynapsys.homeautomation.webservice.Device;
import de.cynapsys.homeautomation.webservice.ObjectFactory;
import de.cynapsys.homeautomation.webservice.Room;
import de.cynapsys.homeautomation.webservice.RoomArray;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.1
 * 
 */
@WebService(name = "RoomWebService", targetNamespace = "http://webservice.homeautomation.cynapsys.de/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RoomWebService {


    /**
     * 
     * @param room
     * @return
     *     returns long
     */
    @WebMethod
    @WebResult(partName = "return")
    public long addRoom(
        @WebParam(name = "room", partName = "room")
        Room room);

    /**
     * 
     * @param roomID
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    public boolean deleteRoom(
        @WebParam(name = "roomID", partName = "roomID")
        long roomID);

    /**
     * 
     * @param room
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    public boolean updateRoom(
        @WebParam(name = "room", partName = "room")
        Room room);

    /**
     * 
     * @return
     *     returns de.cynapsys.homeautomation.webservice.RoomArray
     */
    @WebMethod
    @WebResult(partName = "return")
    public RoomArray getAllRooms();

    /**
     * 
     * @param roomID
     * @return
     *     returns de.cynapsys.homeautomation.webservice.Room
     */
    @WebMethod
    @WebResult(partName = "return")
    public Room getRoomById(
        @WebParam(name = "roomID", partName = "roomID")
        long roomID);

    /**
     * 
     * @param device
     * @param roomID
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    public boolean attachDeviceToRoom(
        @WebParam(name = "device", partName = "device")
        Device device,
        @WebParam(name = "roomID", partName = "roomID")
        long roomID);

    /**
     * 
     * @param device
     * @param roomID
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    public boolean detachDeviceFromRoom(
        @WebParam(name = "device", partName = "device")
        Device device,
        @WebParam(name = "roomID", partName = "roomID")
        long roomID);

}
